name: Deploy
on: workflow_dispatch
jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   run: ls -la
            -   uses: actions/checkout@master
            -   run: ls -la
 
            -   run: sudo apt-get install rsync
            
            -   name: Deploy theme on server
            
                uses: Pendect/action-rsyncer@v1.1.0
                env:
                    DEPLOY_KEY: ${{secrets.SSH_KEY}}
                with:
                    flags: '-avc --delete'
                    src: '/'
                    dest: 'root@"${{secrets.SSH_HOST}}":/var/'
