name: Deploy_to_Prod
on: workflow_dispatch
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
            -   run: sudo apt-get install rsync
            -   name: Setup Node
                uses: actions/setup-node@v3
                with:
                    node-version: 19.7.0
            -   name: Build
                run: |
                    npm install 
                    npm run build
            -   name: Deployment
                uses: Pendect/action-rsyncer@v1.1.0
                env:
                    DEPLOY_KEY: ${{secrets.SSH_KEY}}
                with:
                    flags: "-avc --delete"
                    src: "/build/"
                    dest: "root@'${{secrets.SSH_HOST}}':/var/www/html/"
