name: Deploy_to_Prod
on: workflow_dispatch
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
            -   run: sudo apt-get install rsync
            -   run: npm
            -   name: Setup Node
                uses: actions/setup-node@v3
                with:
                    node-version: 19.7.0
            -   run: npm
            -   name: Deployment
                uses: Pendect/action-rsyncer@v1.1.0
                env:
                    DEPLOY_KEY: ${{secrets.SSH_KEY}}
                with:
                    flags: '-avc --delete --exclude "1README.md"'
                    src: '/'
                    dest: 'root@"${{secrets.SSH_HOST}}":/ali'
