name: Deploy
on: workflow_dispatch
jobs:
  ali:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: alishka1
      uses: appleboy/scp-action@master
      with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USER }}
         port: ${{ secrets.SSH_PORT }}
         key: ${{ secrets.SSH_KEY }}
         source: "/"
         target: "/var"
