name: Deploy_to_Prod

on: [repository_dispatch, workflow_dispatch, push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      -  name: Checkout
         uses: actions/checkout@v4
      
      -  name: Setup Node js
         uses: actions/setup-node@v4
         with:
           node-version: 20.x
           
      -  name: Build Project
         run: |
           sudo apt-get install rsync
           npm install
           npm run build
           
      -  name: Deployment on server
         uses: Pendect/action-rsyncer@v1.1.0

         env:
           DEPLOY_KEY: ${{secrets.SSH_KEY}}
           
         with:
           flags: "-avc --delete"
           src: "/build/"
           dest: "'${{asecrets.SSH_USER}}'@'${{secrets.SSH_HOST}}':'${{secrets.SSH_PORT}}'/var/www/html/"
